services:
  - type: web
    name: telegram-bot
    runtime: python
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: API_ID
        value: 20102665
      - key: API_HASH
        value: aa7944e9d15ae957f2163351dd09d3a6
      - key: BOT_TOKEN
        value: 7998832927:AAHGHwuRBKHMd0hyCI5h_DVAesA0w-Q2fQA
      - key: GOOGLE_API_KEY
        value: AIzaSyAUHdWaph8Hqw0tJyLfSvkkkqyqcxokOiQ
